apiVersion: v1
kind: Template
metadata:
  name: malware-detection-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: malware
    spec:
      envName: ${ENV_NAME}
      title: Malware
      deploymentRepo: https://github.com/RedHatInsights/malware-detection-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/malware-detection
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "malware"
          title: "Malware"
          href: "/insights/malware"
          product: "Red Hat Insights"
          expandable: true
          routes:
            - appId: 'malware'
              title: 'Signatures'
              href: '/insights/malware/signatures'
            - appId: 'malware'
              title: 'Systems'
              href: '/insights/malware/systems'
      module:
        manifestLocation: "/apps/malware/fed-mods.json"
        modules:
          - id: "malware"
            module: "./RootApp"
            routes:
              - pathname: /insights/malware

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-malware/malware-detection-frontend
